/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package so.barbeiro.view;

import barbearia.Barbearia;
import barbearia.Barbeiro;
import barbearia.Cliente;
import barbearia.GeradorClientes;
import barbearia.Main;
import static barbearia.Main.EscreveRelatorio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Random;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    public static final Logger LOG = Logger.getLogger(MainFrame.class.getName());
    
    private int cadeiras;
    private int maxClientes;
    private int mode; //1, 2, 3
    private boolean useMilis;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //Seta janela para o meio da tela, independente da resolução.
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        BufferedPaneOutputStream outStream = new BufferedPaneOutputStream(Console);
        PaneHandler hndlr = new PaneHandler(outStream, new SOFormatter());
        LOG.addHandler(hndlr);
        LOG.setUseParentHandlers(false);
    }

    public JTextPane getConsole(){
        return Console;
    }
    
    private void runProblem(){
        Barbearia barbearia = new Barbearia(this);
        boolean H = EscreveRelatorio();
        if (!H) {
            JOptionPane.showMessageDialog(null, "Erro na criação do arquivo.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else {
            if (!problemParams()) return;
            
            Main.randomGenerator = new Random();
            barbearia.cadeiras = cadeiras;
            barbearia.clientes = maxClientes;
            
            tablesInit(cadeiras);
            
            LOG.info("Barbearia aberta...");
            
            Main.writer.println("Abrindo Barbearia\n");
            Main.writer.println("Cadeiras de espera: " + barbearia.cadeiras + "\n");
            Main.writer.println("Clientes ate finalizacao: " + barbearia.clientes + "\n");
            Main.writer.println("-----------------------------\n");
            Thread b = new Thread(new Barbeiro(barbearia, this, mode, useMilis));
            Thread g = new Thread(new GeradorClientes(barbearia, this, mode, useMilis));
            b.start(); //Inicia Threads
            g.start();
        }
    }
    
    private void tablesInit(int cadeiras){
        DefaultTableModel model = (DefaultTableModel)CadeirasTable.getModel();
        model.setRowCount(cadeiras);
        
        model = (DefaultTableModel)AtendidosTable.getModel();
        model.setRowCount(0);
        
        model = (DefaultTableModel)ClientesNaoAtendidosTable.getModel();
        model.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstadoBarbeiroPanel = new javax.swing.JPanel();
        CadeirasLabel = new javax.swing.JLabel();
        CadeirasField = new javax.swing.JTextField();
        MaxCliLabel = new javax.swing.JLabel();
        MaxCLField = new javax.swing.JTextField();
        Barbeiro = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AtendidosField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NaoAntedidosField = new javax.swing.JTextField();
        CadeirasPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CadeirasTable = new javax.swing.JTable();
        AtendidosPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AtendidosTable = new javax.swing.JTable();
        ClientesNaoAtendidosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientesNaoAtendidosTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EstadoBarbeiroPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Barbearia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        CadeirasLabel.setText("Cadeiras");

        CadeirasField.setText("9999");

        MaxCliLabel.setText("Max. Clientes");

        MaxCLField.setText("9999");

        Barbeiro.setSelected(true);
        Barbeiro.setText("Dormindo");

        jLabel1.setText("Barbeiro:");

        jLabel2.setText("Atendidos");

        AtendidosField.setText("9999");

        jLabel3.setText("Não atendidos");

        NaoAntedidosField.setText("9999");

        javax.swing.GroupLayout EstadoBarbeiroPanelLayout = new javax.swing.GroupLayout(EstadoBarbeiroPanel);
        EstadoBarbeiroPanel.setLayout(EstadoBarbeiroPanelLayout);
        EstadoBarbeiroPanelLayout.setHorizontalGroup(
            EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoBarbeiroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadoBarbeiroPanelLayout.createSequentialGroup()
                        .addComponent(CadeirasLabel)
                        .addGap(12, 12, 12)
                        .addComponent(CadeirasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MaxCliLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaxCLField))
                    .addGroup(EstadoBarbeiroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AtendidosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NaoAntedidosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EstadoBarbeiroPanelLayout.setVerticalGroup(
            EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoBarbeiroPanelLayout.createSequentialGroup()
                .addGroup(EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barbeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EstadoBarbeiroPanelLayout.createSequentialGroup()
                        .addGroup(EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NaoAntedidosField)
                            .addGroup(EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AtendidosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EstadoBarbeiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadeirasLabel)
                            .addComponent(CadeirasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaxCliLabel)
                            .addComponent(MaxCLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        CadeirasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadeiras da barbearia"));

        CadeirasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome do Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CadeirasTable);

        javax.swing.GroupLayout CadeirasPanelLayout = new javax.swing.GroupLayout(CadeirasPanel);
        CadeirasPanel.setLayout(CadeirasPanelLayout);
        CadeirasPanelLayout.setHorizontalGroup(
            CadeirasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        CadeirasPanelLayout.setVerticalGroup(
            CadeirasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadeirasPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AtendidosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes atendidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        AtendidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome do Cliente", "Tempo de atendimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(AtendidosTable);

        javax.swing.GroupLayout AtendidosPanelLayout = new javax.swing.GroupLayout(AtendidosPanel);
        AtendidosPanel.setLayout(AtendidosPanelLayout);
        AtendidosPanelLayout.setHorizontalGroup(
            AtendidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        AtendidosPanelLayout.setVerticalGroup(
            AtendidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        ClientesNaoAtendidosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes não atendidos"));

        ClientesNaoAtendidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome do Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClientesNaoAtendidosTable);

        javax.swing.GroupLayout ClientesNaoAtendidosPanelLayout = new javax.swing.GroupLayout(ClientesNaoAtendidosPanel);
        ClientesNaoAtendidosPanel.setLayout(ClientesNaoAtendidosPanelLayout);
        ClientesNaoAtendidosPanelLayout.setHorizontalGroup(
            ClientesNaoAtendidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        ClientesNaoAtendidosPanelLayout.setVerticalGroup(
            ClientesNaoAtendidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        Console.setEditable(false);
        Console.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Console", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane3.setViewportView(Console);

        jMenu1.setText("Run");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setText("Run problem");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadeirasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClientesNaoAtendidosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EstadoBarbeiroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AtendidosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClientesNaoAtendidosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadeirasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstadoBarbeiroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AtendidosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Console.setText("");
        Console.setCaretPosition(0);
        runProblem();
        setBarberState(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Inicia o dialog para obter os
     * params. do problema.
     * @return True se usuário quis executar.
     *         False se usuário cancelou.
     */
    private boolean problemParams (){
        this.setEnabled(false);
        InitDialog diag = new InitDialog(this);//.setVisible(true);
        diag.setVisible(true);
        boolean validVars = diag.isValidVariables();
        diag.dispose();
        return validVars;
    }

    public void setCadeiras(int cadeiras) {
        this.cadeiras = cadeiras;
        CadeirasField.setText(Integer.toString(cadeiras));
    }

    public void setMaxClientes(int maxClientes) {
        this.maxClientes = maxClientes;
        MaxCLField.setText(Integer.toString(maxClientes));
    }

    public void setMode(int mode) {
        if (mode<1 || mode>6) throw new IllegalArgumentException("Modo inválido!");
        this.mode = mode;
    }

    
    public void setUseMilis(boolean useMilis) {
        this.useMilis = useMilis;
    }
    
    public void fillFila(ArrayList<Cliente> cls){
        DefaultTableModel model = (DefaultTableModel)CadeirasTable.getModel();
        model.setRowCount(0);
        cls.stream().forEach((cli) -> {
            model.addRow(cli.getFila());
        });
    }
    
    public void fillNaoAtendidos(ArrayList<Cliente> cls){
        DefaultTableModel model = (DefaultTableModel)ClientesNaoAtendidosTable.getModel();
        model.setRowCount(0);
        cls.stream().forEach((cli) -> {
            model.addRow(cli.getNaoAtendido());
        });
        NaoAntedidosField.setText(Integer.toString(cls.size()));
    }
    
    public void fillAtendidos(ArrayList<Cliente> cls){
        DefaultTableModel model = (DefaultTableModel)AtendidosTable.getModel();
        model.setRowCount(0);
        cls.stream().forEach((Cliente cli) -> {
            model.addRow(cli.getAtendido());
        });
        AtendidosField.setText(Integer.toString(cls.size()));
    }
    
    /**
     * Troca a cor do estado do barbeiro.
     * @param state 0 - Dormindo.
     *              1 - Atendendo.
     */
    public void setBarberState(int state){
        if (state == 0){
            Color color = new Color(0,0,220);
            Barbeiro.setBackground(color);
            //Barbeiro.setForeground(color);
            Barbeiro.setText("Dormindo");
        } else if (state == 1){
            Color color = new Color(0,220,0);
            Barbeiro.setBackground(color);
            //Barbeiro.setForeground(color);
            Barbeiro.setText("Atendendo");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AtendidosField;
    private javax.swing.JPanel AtendidosPanel;
    private javax.swing.JTable AtendidosTable;
    private javax.swing.JToggleButton Barbeiro;
    private javax.swing.JTextField CadeirasField;
    private javax.swing.JLabel CadeirasLabel;
    private javax.swing.JPanel CadeirasPanel;
    private javax.swing.JTable CadeirasTable;
    private javax.swing.JPanel ClientesNaoAtendidosPanel;
    private javax.swing.JTable ClientesNaoAtendidosTable;
    private javax.swing.JTextPane Console;
    private javax.swing.JPanel EstadoBarbeiroPanel;
    private javax.swing.JTextField MaxCLField;
    private javax.swing.JLabel MaxCliLabel;
    private javax.swing.JTextField NaoAntedidosField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
